// Codegen: derives packages/shared's Zod schemas from packages/db's Drizzle
// table definitions, so field shape (name, base type, nullability, identity)
// has one source of truth instead of two hand-maintained copies. Run via
// `bun run codegen` (wired into `typecheck`/`build`, matching apps/web's
// `tsr generate` pattern) — never edit the *.gen.ts output by hand.
//
// What's NOT derivable from Drizzle alone: numeric bound strictness
// (positive vs. nonnegative vs. unbounded) is a business decision with no
// structural signal in a plain SQL integer/double column — see OVERRIDES
// below. Everything else (base type, nullability, identity-column-as-
// positive-int) is fully structural.

import {
	ballPositions,
	competitions,
	fixtures,
	matchEvents,
	playerSeasonStats,
	players,
	seasons,
	teams,
} from "@console-next/db/schema";
import { type Column, getTableColumns } from "drizzle-orm";

type Table = Parameters<typeof getTableColumns>[0];

interface EntityConfig {
	table: Table;
	fileName: string;
	schemaName: string;
	typeName: string;
}

// Scoped per-entity, not global — a field name like `x` shouldn't silently
// apply its override to some future unrelated entity.
type Bound = "positive" | "unbounded";
const OVERRIDES: Record<string, Record<string, Bound>> = {
	"ball-position": { x: "unbounded", y: "unbounded" },
};

const ENTITIES: Record<string, EntityConfig> = {
	team: {
		table: teams,
		fileName: "team",
		schemaName: "TeamSchema",
		typeName: "Team",
	},
	competition: {
		table: competitions,
		fileName: "competition",
		schemaName: "CompetitionSchema",
		typeName: "Competition",
	},
	fixture: {
		table: fixtures,
		fileName: "fixture",
		schemaName: "FixtureSchema",
		typeName: "Fixture",
	},
	season: {
		table: seasons,
		fileName: "season",
		schemaName: "SeasonSchema",
		typeName: "Season",
	},
	player: {
		table: players,
		fileName: "player",
		schemaName: "PlayerSchema",
		typeName: "Player",
	},
	"match-event": {
		table: matchEvents,
		fileName: "match-event",
		schemaName: "MatchEventSchema",
		typeName: "MatchEvent",
	},
	"ball-position": {
		table: ballPositions,
		fileName: "ball-position",
		schemaName: "BallPositionSchema",
		typeName: "BallPosition",
	},
	"player-season-stats": {
		table: playerSeasonStats,
		fileName: "player-season-stats",
		schemaName: "PlayerSeasonStatsSchema",
		typeName: "PlayerSeasonStats",
	},
};

const mapColumn = (
	entityKey: string,
	fieldName: string,
	col: Column,
): string => {
	let expr: string;

	switch (col.columnType) {
		case "PgInteger":
		case "PgDoublePrecision": {
			const numeric =
				col.columnType === "PgInteger" ? "z.number().int()" : "z.number()";
			const isIdentity = col.primary && !!col.generatedIdentity;
			const looksLikeId = /Id$/.test(fieldName) || fieldName === "id";
			const override = OVERRIDES[entityKey]?.[fieldName];

			if (override === "unbounded") {
				expr = numeric;
			} else if (override === "positive" || isIdentity || looksLikeId) {
				expr = `${numeric}.positive()`;
			} else {
				expr = `${numeric}.nonnegative()`;
			}
			break;
		}
		case "PgText":
			expr = "z.string()";
			break;
		case "PgBoolean":
			expr = "z.boolean()";
			break;
		case "PgDateString":
			expr = "z.iso.date()";
			break;
		case "PgTimestamp":
			// Always ISO string at the JSON boundary, regardless of Drizzle's own
			// column mode (which stays Date-typed for DB/query-layer ergonomics —
			// see PROJECT.md's "different layers, not a conflict" note).
			expr = "z.iso.datetime()";
			break;
		default:
			throw new Error(
				`generate-schemas: no mapping for column type "${col.columnType}" (${entityKey}.${fieldName}) — add one before regenerating.`,
			);
	}

	if (!col.notNull) {
		expr += ".nullable()";
	}

	return expr;
};

const generateFile = (entityKey: string, config: EntityConfig): string => {
	const columns = getTableColumns(config.table);
	const fields = Object.entries(columns)
		.map(
			([fieldName, col]) =>
				`\t${fieldName}: ${mapColumn(entityKey, fieldName, col as Column)},`,
		)
		.join("\n");

	return `// AUTO-GENERATED by packages/shared/scripts/generate-schemas.ts — DO NOT EDIT.
// Source of truth: packages/db/src/schema/${entityKey}.ts
import { z } from "zod";

export const ${config.schemaName} = z.object({
${fields}
});

export type ${config.typeName} = z.infer<typeof ${config.schemaName}>;
`;
};

for (const [entityKey, config] of Object.entries(ENTITIES)) {
	const outPath = `${import.meta.dir}/../src/schemas/${config.fileName}.gen.ts`;
	await Bun.write(outPath, generateFile(entityKey, config));
	console.log(`generated src/schemas/${config.fileName}.gen.ts`);
}
